install.packages("readr")
install.packages("readxl")
install.packages("xlsx")
install.packages("tidyr")
install.packages("dplyr")
install.packages("plyr")
install.packages("foreign")
install.packages("matrixStats")
install.packages("reshape")
install.packages("readstata13")
install.packages("countrycode")
install.packages("cshapes")
install.packages("mefa")

